FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y texlive-latex-base texlive-latex-extra && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN pip install .

CMD pdflatex result.tex
